# Generated by Django 5.1.2 on 2024-11-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Titre par défaut', max_length=255),
        ),
    ]
